# Generated by Django 4.0.4 on 2022-05-11 19:24

from django.db import migrations, models

#codigo mas generico no es SQL, el enginee que va a utiizar es el que indicamos en settings DATABSASE

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]

# en consola: python .\manage.py sqlmigrate personas 0001
#DJANGO CREA LA CLAVE PRIMARIA ID
#Deesp de vuelta se hace python manage.py migrate y ahi se crea